import type { Activity } from "./storage";

/** Editorial programme borrowed from newexhibitions.com (mixed archive + current). */
export const EDITORIAL_ACTIVITIES: Activity[] = [
  {
    id: "ne-33158",
    activity_title: "Shot In Soho",
    author_name: "The Photographers\u2019 Gallery",
    username: "the_photographers_gallery",
    activity_location: "The Photographers\u2019 Gallery, London",
    activity_date: "18 Oct 2019-9 Feb 2020",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "The Photographers\u2019 Gallery",
    website_link: "https://www.thephotographersgallery.org.uk",
    body_text_1: "<p>'Shot in Soho' is an original exhibition celebrating Soho\u2019s diverse culture, community and history of creative innovation as well as highlighting its position as a site of resistance. Although the area of Soho is relatively small (one square mile) and bordered by some of London\u2019s richest and most commercialised streets, it has remained a complex place of unorthodoxy, diversity, tolerance and defiance. Including works by William Klein, Anders Petersen, Corrine Day, alongside other photographers whose work in Soho is lesser known such as Daragh Soden and Clancy Gebler Davies.</p>",
    body_text_2: "<p>Venue: The Photographers\u2019 Gallery. Dates: 18 Oct 2019-9 Feb 2020.</p>",
    activity_description: "'Shot in Soho' is an original exhibition celebrating Soho\u2019s diverse culture, community and history of creative innovation as well as highlighting its position as a site of resistance. Although the area of Soho is relatively small (one square mile) and bordered by some of London\u2019s richest and most commercialised streets, it has remained a complex place of unorthodoxy, diversity, tolerance and defiance. Including works by William Klein, Anders Petersen, Corrine Day, alongside other photographers whose work in Soho is lesser known such as Daragh Soden and Clancy Gebler Davies.",
    organizer: "The Photographers\u2019 Gallery",
    partner: "The Photographers\u2019 Gallery",
    primary_image: "https://www.newexhibitions.com/uploads/2/e/large/607d7ca6b069d.jpg",
    additional_images_1: "https://www.newexhibitions.com/uploads/2/e/large/607d7ca6b069d.jpg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/2/e/large/607d7ca6b069d.jpg"],
    createdAt: "2006-01-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-20435",
    activity_title: "Into the Night : Cabarets & Clubs in Modern Art",
    author_name: "Barbican Art Gallery",
    username: "barbican_art_gallery",
    activity_location: "Barbican Art Gallery, London",
    activity_date: "4 Oct 2019-19 Jan 2020",
    activity_type: "Exhibition",
    activity_area: "East London",
    partner_name: "Barbican Art Gallery",
    website_link: "https://barbican.org.uk/artgallery",
    body_text_1: "<p>This landmark exhibition explores the electrifying history of cabarets, caf\u00e9s and clubs in modern art across the world, from London to New York, Paris, Mexico City, Berlin, Vienna and Ibadan. Discover over 200 works of art, many rarely seen in the UK, as well as life-size recreations of avant-garde spaces.</p>",
    body_text_2: "<p>Venue: Barbican Art Gallery. Dates: 4 Oct 2019-19 Jan 2020.</p>",
    activity_description: "This landmark exhibition explores the electrifying history of cabarets, caf\u00e9s and clubs in modern art across the world, from London to New York, Paris, Mexico City, Berlin, Vienna and Ibadan. Discover over 200 works of art, many rarely seen in the UK, as well as life-size recreations of avant-garde spaces.",
    organizer: "Barbican Art Gallery",
    partner: "Barbican Art Gallery",
    primary_image: "https://www.newexhibitions.com/uploads/1/a/large/607d72baa8c2a.jpg",
    additional_images_1: "https://www.newexhibitions.com/uploads/1/a/large/607d72baa8c2a.jpg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/1/a/large/607d72baa8c2a.jpg"],
    createdAt: "2008-02-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-30700",
    activity_title: "THE RITA KEEGAN ARCHIVE (PROJECT)",
    author_name: "South London Gallery",
    username: "south_london_gallery",
    activity_location: "South London Gallery, London",
    activity_date: "15 Aug-13 Sep 2020",
    activity_type: "Exhibition",
    activity_area: "South London",
    partner_name: "South London Gallery",
    website_link: "https://www.southlondongallery.org",
    body_text_1: "<p>Artist, lecturer and archivist Rita Keegan\u2019s practice reflects the intersection of new media experimentation, feminist practice and the Black Arts Movement of the 1980s. In 1985, Keegan established the Women Artists of Colour Index (WOCI), a unique collection of slides and papers that provides a vital historical resource for contemporary discussions of race and gender. This display in the SLG\u2019s Archive room features Keegan\u2019s personal papers, offering a rare opportunity to see a range of materials and ephemera from the Black British Art scene spanning the 1980s to the early 2000s.</p>",
    body_text_2: "<p>Venue: South London Gallery. Dates: 15 Aug-13 Sep 2020.</p>",
    activity_description: "Artist, lecturer and archivist Rita Keegan\u2019s practice reflects the intersection of new media experimentation, feminist practice and the Black Arts Movement of the 1980s. In 1985, Keegan established the Women Artists of Colour Index (WOCI), a unique collection of slides and papers that provides a vital historical resource for contemporary discussions of race and gender. This display in the SLG\u2019s Archive room features Keegan\u2019s personal papers, offering a rare opportunity to see a range of materials and ephemera from the Black British Art scene spanning the 1980s to the early 2000s.",
    organizer: "South London Gallery",
    partner: "South London Gallery",
    primary_image: "https://www.newexhibitions.com/uploads/3/c/large/655b7a0642211.jpeg",
    additional_images_1: "https://www.newexhibitions.com/uploads/3/c/large/655b7a0642211.jpeg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/3/c/large/655b7a0642211.jpeg"],
    createdAt: "2010-03-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-29966",
    activity_title: "TUTANKHAMUN : Treasures of the Golden Pharaoh",
    author_name: "Saatchi Gallery",
    username: "saatchi_gallery",
    activity_location: "Saatchi Gallery, London",
    activity_date: "2 Nov 2019-3 May 2020",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Saatchi Gallery",
    website_link: "https://www.saatchigallery.com",
    body_text_1: "<p>'TUTANKHAMUN: Treasures of the Golden Pharaoh Celebrates the Centenary of Howard Carter's Discovery'. Unprecedented Collection Coming to Saatchi Gallery in November. Commemorating the centenary of the discovery that captivated the world, the largest collection of King Tutankhamun's treasures ever to travel out of Egypt will open at the Saatchi Gallery in London for a limited run beginning Saturday 2 November 2019, and until 3 May 2020.</p>",
    body_text_2: "<p>Venue: Saatchi Gallery. Dates: 2 Nov 2019-3 May 2020.</p>",
    activity_description: "'TUTANKHAMUN: Treasures of the Golden Pharaoh Celebrates the Centenary of Howard Carter's Discovery'. Unprecedented Collection Coming to Saatchi Gallery in November. Commemorating the centenary of the discovery that captivated the world, the largest collection of King Tutankhamun's treasures ever to travel out of Egypt will open at the Saatchi Gallery in London for a limited run beginning Saturday 2 November 2019, and until 3 May 2020.",
    organizer: "Saatchi Gallery",
    partner: "Saatchi Gallery",
    primary_image: "https://www.newexhibitions.com/uploads/8/d/large/607d7a1ec53a2.jpg",
    additional_images_1: "https://www.newexhibitions.com/uploads/8/d/large/607d7a1ec53a2.jpg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/8/d/large/607d7a1ec53a2.jpg"],
    createdAt: "2012-04-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-27000",
    activity_title: "Interventions",
    author_name: "Lewisham Arthouse",
    username: "lewisham_arthouse",
    activity_location: "Lewisham Arthouse, London",
    activity_date: "31 Aug-11 Sep 2016",
    activity_type: "Exhibition",
    activity_area: "South London",
    partner_name: "Lewisham Arthouse",
    website_link: "https://www.lewishamarthouse.org.uk",
    body_text_1: "<p>The nine artists in this group exhibition are exploring the idea of interventions within the gallery space. Their individual practices, through a variety of different languages and media, are very diverse, yet the artists search to reveal a dialogue, a connection and thread. The group are interested in the relationships between how their works create a visual discourse and how by placing their works within a common space the interventions of their works create yet another layer and language. These artists are searching for hidden dynamics that create new understandings, correlations and connections.</p>",
    body_text_2: "<p>Venue: Lewisham Arthouse. Dates: 31 Aug-11 Sep 2016.</p>",
    activity_description: "The nine artists in this group exhibition are exploring the idea of interventions within the gallery space. Their individual practices, through a variety of different languages and media, are very diverse, yet the artists search to reveal a dialogue, a connection and thread. The group are interested in the relationships between how their works create a visual discourse and how by placing their works within a common space the interventions of their works create yet another layer and language. These artists are searching for hidden dynamics that create new understandings, correlations and connections.",
    organizer: "Lewisham Arthouse",
    partner: "Lewisham Arthouse",
    primary_image: "https://www.newexhibitions.com/uploads/c/d/large/607d78118bc31.jpg",
    additional_images_1: "https://www.newexhibitions.com/uploads/c/d/large/607d78118bc31.jpg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/c/d/large/607d78118bc31.jpg"],
    createdAt: "2014-05-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-25000",
    activity_title: "Ben Ravenscroft : Great Outdoors",
    author_name: "Ben Ravenscroft",
    username: "ben_ravenscroft",
    activity_location: "Hales, London",
    activity_date: "19 Oct-17 Nov 2007",
    activity_type: "Exhibition",
    activity_area: "East London",
    partner_name: "Hales",
    website_link: "https://www.halesgallery.com",
    body_text_1: "<p>New paintings on aluminium develop the artist's complex enquiry into painting's founding material and aesthetic categories.</p>",
    body_text_2: "<p>Venue: Hales. Dates: 19 Oct-17 Nov 2007.</p>",
    activity_description: "New paintings on aluminium develop the artist's complex enquiry into painting's founding material and aesthetic categories.",
    organizer: "Hales",
    partner: "Hales",
    primary_image: "https://www.newexhibitions.com/uploads/3/f/large/607d7664c242f.jpg",
    additional_images_1: "https://www.newexhibitions.com/uploads/3/f/large/607d7664c242f.jpg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/3/f/large/607d7664c242f.jpg"],
    createdAt: "2016-06-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-20000",
    activity_title: "Mixed Doubles",
    author_name: "Art First",
    username: "art_first",
    activity_location: "Art First, London",
    activity_date: "12 Jul-19 Aug 2005",
    activity_type: "Exhibition",
    activity_area: "East London",
    partner_name: "Art First",
    website_link: "https://www.artfirst.co.uk",
    body_text_1: "<p>Gallery artists, whose partners are fellow artists, have been invited to exhibit together in this exploration of critical dialogues.</p>",
    body_text_2: "<p>Venue: Art First. Dates: 12 Jul-19 Aug 2005.</p>",
    activity_description: "Gallery artists, whose partners are fellow artists, have been invited to exhibit together in this exploration of critical dialogues.",
    organizer: "Art First",
    partner: "Art First",
    primary_image: "https://www.newexhibitions.com/uploads/0/7/large/641c76f9d4ab6.jpeg",
    additional_images_1: "https://www.newexhibitions.com/uploads/0/7/large/641c76f9d4ab6.jpeg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/0/7/large/641c76f9d4ab6.jpeg"],
    createdAt: "2018-07-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69236",
    activity_title: "Into the Surface: Defne Tesal and Stephan Baumk\u00f6tter",
    author_name: "Bartha Contemporary",
    username: "bartha_contemporary",
    activity_location: "Bartha Contemporary, London",
    activity_date: "24 Sep-18 Oct 2026",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Bartha Contemporary",
    website_link: "https://www.barthacontemporary.com",
    body_text_1: "<p>Bartha Contemporary is pleased to present Into the Surface , a two-person exhibition bringing together recent works by Defne Tesal and Stephan Baumk\u00f6tter. Six works from Tesal\u2019s Door series, made in 2025, are shown alongside five small-format paintings by Baumk\u00f6tter from 2019. Distinct in material and method, both bodies of work create a subtle sense of depth through repeated gestures, layered surfaces and a tactile handling of colour.</p>",
    body_text_2: "<p>Venue: Bartha Contemporary. Dates: 24 Sep-18 Oct 2026.</p>",
    activity_description: "Bartha Contemporary is pleased to present Into the Surface , a two-person exhibition bringing together recent works by Defne Tesal and Stephan Baumk\u00f6tter. Six works from Tesal\u2019s Door series, made in 2025, are shown alongside five small-format paintings by Baumk\u00f6tter from 2019. Distinct in material and method, both bodies of work create a subtle sense of depth through repeated gestures, layered surfaces and a tactile handling of colour.",
    organizer: "Bartha Contemporary",
    partner: "Bartha Contemporary",
    primary_image: "https://www.newexhibitions.com/uploads/0/5/large/6aa400b2d2568.png",
    additional_images_1: "https://www.newexhibitions.com/uploads/0/5/large/6aa400b2d2568.png",
    additional_images_2: ["https://www.newexhibitions.com/uploads/0/5/large/6aa400b2d2568.png"],
    createdAt: "2026-08-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69229",
    activity_title: "Pastels",
    author_name: "Maximillian William",
    username: "maximillian_william",
    activity_location: "Maximillian William, London",
    activity_date: "17 Sep-14 Nov 2026 PV 17 Sep 2026, 6-8pm",
    activity_type: "Exhibition",
    activity_area: "East London",
    partner_name: "Maximillian William",
    website_link: "https://maximillianwilliam.com",
    body_text_1: "<p>Maximillian William is pleased to present a new collection of eight soft-pastels on paper by Somaya Critchlow. The works in this presentation show Critchlow\u2019s ongoing exploration of the materiality of pigment, with the medium allowing for a fragmentation and softening of her characteristically alluring and at times uncanny portraits. In these small-scale images, women are shown in gentle interiors or indefinite spaces, their poses and expressions adding to a language that feels at home within the painter\u2019s oeuvre.</p>",
    body_text_2: "<p>Venue: Maximillian William. Dates: 17 Sep-14 Nov 2026 PV 17 Sep 2026, 6-8pm.</p>",
    activity_description: "Maximillian William is pleased to present a new collection of eight soft-pastels on paper by Somaya Critchlow. The works in this presentation show Critchlow\u2019s ongoing exploration of the materiality of pigment, with the medium allowing for a fragmentation and softening of her characteristically alluring and at times uncanny portraits. In these small-scale images, women are shown in gentle interiors or indefinite spaces, their poses and expressions adding to a language that feels at home within the painter\u2019s oeuvre.",
    organizer: "Maximillian William",
    partner: "Maximillian William",
    primary_image: "https://www.newexhibitions.com/uploads/4/0/large/6aa3cfa5d8baa.jpeg",
    additional_images_1: "https://www.newexhibitions.com/uploads/4/0/large/6aa3cfa5d8baa.jpeg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/4/0/large/6aa3cfa5d8baa.jpeg"],
    createdAt: "2026-09-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69220",
    activity_title: "Madelon Vriesendorp: Mind Games",
    author_name: "Madelon Vriesendorp",
    username: "madelon_vriesendorp",
    activity_location: "Sir John Soane\u2019s Museum, London",
    activity_date: "15 Jan-20 Sep 2026",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Sir John Soane\u2019s Museum",
    website_link: "https://www.soane.org",
    body_text_1: "<p>A major retrospective celebrating the surreal, subversive practice of artist Madelon Vriesendorp is now open at Sir John Soane\u2019s Museum.</p>",
    body_text_2: "<p>Venue: Sir John Soane\u2019s Museum. Dates: 15 Jan-20 Sep 2026.</p>",
    activity_description: "A major retrospective celebrating the surreal, subversive practice of artist Madelon Vriesendorp is now open at Sir John Soane\u2019s Museum.",
    organizer: "Sir John Soane\u2019s Museum",
    partner: "Sir John Soane\u2019s Museum",
    primary_image: "https://www.newexhibitions.com/uploads/6/9/large/6aa2b01824bbb.png",
    additional_images_1: "https://www.newexhibitions.com/uploads/6/9/large/6aa2b01824bbb.png",
    additional_images_2: ["https://www.newexhibitions.com/uploads/6/9/large/6aa2b01824bbb.png"],
    createdAt: "2026-10-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69215",
    activity_title: "Evelyn Taocheng Wang: Relaxed viewing",
    author_name: "Evelyn Taocheng Wang",
    username: "evelyn_taocheng_wang",
    activity_location: "Goldsmiths Centre for Contemporary Art, London",
    activity_date: "2 Dec 2026",
    activity_type: "Exhibition",
    activity_area: "South London",
    partner_name: "Goldsmiths Centre for Contemporary Art",
    website_link: "https://www.newexhibitions.com/e/69215",
    body_text_1: "<p>Evelyn Taocheng Wang\u2019s exhibition Being Poetic Ruins Life will open an hour early on the first Wednesday of each month to prioritise the experience of those who may wish to visit the exhibition with certain adjustments.</p>",
    body_text_2: "<p>Venue: Goldsmiths Centre for Contemporary Art. Dates: 2 Dec 2026.</p>",
    activity_description: "Evelyn Taocheng Wang\u2019s exhibition Being Poetic Ruins Life will open an hour early on the first Wednesday of each month to prioritise the experience of those who may wish to visit the exhibition with certain adjustments.",
    organizer: "Goldsmiths Centre for Contemporary Art",
    partner: "Goldsmiths Centre for Contemporary Art",
    primary_image: "https://www.newexhibitions.com/uploads/9/5/large/6aa285753bb6c.jpeg",
    additional_images_1: "https://www.newexhibitions.com/uploads/9/5/large/6aa285753bb6c.jpeg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/9/5/large/6aa285753bb6c.jpeg"],
    createdAt: "2026-11-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69207",
    activity_title: "On Felicity Powell",
    author_name: "Richard Saltoun",
    username: "richard_saltoun",
    activity_location: "Richard Saltoun, London",
    activity_date: "29 Sep 2026 6-8pm",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Richard Saltoun",
    website_link: "https://www.richardsaltoun.com",
    body_text_1: "<p>Join us for an in-conversation with Marina Warner & Sarah Turner on the occasion of The Studio of Felicity Powell (1961-2015).</p>",
    body_text_2: "<p>Venue: Richard Saltoun. Dates: 29 Sep 2026 6-8pm.</p>",
    activity_description: "Join us for an in-conversation with Marina Warner & Sarah Turner on the occasion of The Studio of Felicity Powell (1961-2015).",
    organizer: "Richard Saltoun",
    partner: "Richard Saltoun",
    primary_image: "https://www.newexhibitions.com/uploads/5/0/large/6aa18ac8b5645.jpeg",
    additional_images_1: "https://www.newexhibitions.com/uploads/5/0/large/6aa18ac8b5645.jpeg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/5/0/large/6aa18ac8b5645.jpeg"],
    createdAt: "2026-12-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69204",
    activity_title: "Park Nights 2026: Ebun Sodipo and Rosa-Johan Uddoh",
    author_name: "Park Nights 2026",
    username: "park_nights_2026",
    activity_location: "Serpentine, London",
    activity_date: "25 Sep 2026",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Serpentine",
    website_link: "https://www.serpentinegalleries.org",
    body_text_1: "<p>Visual artist and writer Ebun Sodipo and Rosa-Johan Uddoh present a new iteration of Atlantic Cruises (2018-ongoing), their collaborative performance rooted in Black feminist study. Speculating on the drives behind attacks and failures experienced by Black, trans, and queer communities, Sodipo and Uddoh's polyphonic audio-visual conversation maps new languages and tools to speak about the body and the past for Black people of the future.</p>",
    body_text_2: "<p>Venue: Serpentine. Dates: 25 Sep 2026.</p>",
    activity_description: "Visual artist and writer Ebun Sodipo and Rosa-Johan Uddoh present a new iteration of Atlantic Cruises (2018-ongoing), their collaborative performance rooted in Black feminist study. Speculating on the drives behind attacks and failures experienced by Black, trans, and queer communities, Sodipo and Uddoh's polyphonic audio-visual conversation maps new languages and tools to speak about the body and the past for Black people of the future.",
    organizer: "Serpentine",
    partner: "Serpentine",
    primary_image: "https://www.newexhibitions.com/uploads/f/0/large/6aa17a1fcf158.jpeg",
    additional_images_1: "https://www.newexhibitions.com/uploads/f/0/large/6aa17a1fcf158.jpeg",
    additional_images_2: ["https://www.newexhibitions.com/uploads/f/0/large/6aa17a1fcf158.jpeg"],
    createdAt: "2026-01-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-69195",
    activity_title: "Lucy Dodd: The good, the true and the beautiful",
    author_name: "Lucy Dodd",
    username: "lucy_dodd",
    activity_location: "Spr\u00fcth Magers, London",
    activity_date: "18 Sep-24 Oct 2026 PV 17 Sep 2026, 6-8pm",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Spr\u00fcth Magers",
    website_link: "https://www.spruethmagers.com",
    body_text_1: "<p>At the centre of Lucy Dodd\u2019s solo exhibition The good, the true and the beautiful at Spr\u00fcth Magers, London, stands the figure of Diana, the woodland huntress on earth and luminous celestial body in the sky. The figure carries both collective resonance and personal significance for Dodd, whose grandmother bore the name Diana, and extends outward to Diana Spencer, Princess of Wales: a mirror image rather than an equivalent. Where the goddess refused marriage, claimed her freedom and destroyed those who transgressed it, the Princess was hunted for the same desire for autonomy\u2014a dynamic that remains violently unresolved today. Having recently relocated her life and studio from upstate New York to the Moray Coast in Scotland, Dodd draws the materials of her new surroundings directly into the work. Peat collected from the shores of the Findhorn River, copper ink, spirulina, cochineal, local herbs and powdered meteorite form a palette that contains, in material fact, the matter of the forest floor and traces of the cosmos above it. Employing circular formats for the first time, Dodd condenses multiple registers into a single geometry: lunar disc, huntress\u2019 target, eye, breast. Grounding the mythological throughout are indexical traces, such as a child\u2019s footprint or a brush set down and abandoned, leaving behind its impression in the pigment.</p>",
    body_text_2: "<p>Venue: Spr\u00fcth Magers. Dates: 18 Sep-24 Oct 2026 PV 17 Sep 2026, 6-8pm.</p>",
    activity_description: "At the centre of Lucy Dodd\u2019s solo exhibition The good, the true and the beautiful at Spr\u00fcth Magers, London, stands the figure of Diana, the woodland huntress on earth and luminous celestial body in the sky. The figure carries both collective resonance and personal significance for Dodd, whose grandmother bore the name Diana, and extends outward to Diana Spencer, Princess of Wales: a mirror image rather than an equivalent. Where the goddess refused marriage, claimed her freedom and destroyed those who transgressed it, the Princess was hunted for the same desire for autonomy\u2014a dynamic that remains violently unresolved today. Having recently relocated her life and studio from upstate New York to the Moray Coast in Scotland, Dodd draws the materials of her new surroundings directly into the work. Peat collected from the shores of the Findhorn River, copper ink, spirulina, cochineal, local herbs and powdered meteorite form a palette that contains, in material fact, the matter of the forest floor and traces of the cosmos above it. Employing circular formats for the first time, Dodd condenses multiple registers into a single geometry: lunar disc, huntress\u2019 target, eye, breast. Grounding the mythological throughout are indexical traces, such as a child\u2019s footprint or a brush set down and abandoned, leaving behind its impression in the pigment.",
    organizer: "Spr\u00fcth Magers",
    partner: "Spr\u00fcth Magers",
    primary_image: "https://www.newexhibitions.com/uploads/f/3/large/6aa157af8d3c7.png",
    additional_images_1: "https://www.newexhibitions.com/uploads/f/3/large/6aa157af8d3c7.png",
    additional_images_2: ["https://www.newexhibitions.com/uploads/f/3/large/6aa157af8d3c7.png"],
    createdAt: "2026-02-12T12:00:00.000Z",
    is_deleted: false,
  },
  {
    id: "ne-68622",
    activity_title: "Helen Marten: This Weather",
    author_name: "Helen Marten",
    username: "helen_marten",
    activity_location: "Sadie Coles HQ, Savile Row, London",
    activity_date: "27 May-12 Sep 2026 PV 27 May 2026, 6-8pm",
    activity_type: "Exhibition",
    activity_area: "West London",
    partner_name: "Sadie Coles HQ, Savile Row",
    website_link: "https://sadiecoles.com",
    body_text_1: "<p>Opening in May, Helen Marten presents This Weather, a film in five chapters, at Sadie Coles HQ. Originally conceived as part of Marten\u2019s ambitious opera performance,30 Blizzards., presented by Miu Miu at Palais d\u2019I\u00e9na for Art Basel Paris in October 2025, This Weather is restaged here as a singular work.</p>",
    body_text_2: "<p>Venue: Sadie Coles HQ, Savile Row. Dates: 27 May-12 Sep 2026 PV 27 May 2026, 6-8pm.</p>",
    activity_description: "Opening in May, Helen Marten presents This Weather, a film in five chapters, at Sadie Coles HQ. Originally conceived as part of Marten\u2019s ambitious opera performance,30 Blizzards., presented by Miu Miu at Palais d\u2019I\u00e9na for Art Basel Paris in October 2025, This Weather is restaged here as a singular work.",
    organizer: "Sadie Coles HQ, Savile Row",
    partner: "Sadie Coles HQ, Savile Row",
    primary_image: "https://www.newexhibitions.com/uploads/f/7/large/69fa0b4f8d8b6.png",
    additional_images_1: "https://www.newexhibitions.com/uploads/f/7/large/69fa0b4f8d8b6.png",
    additional_images_2: ["https://www.newexhibitions.com/uploads/f/7/large/69fa0b4f8d8b6.png"],
    createdAt: "2026-03-12T12:00:00.000Z",
    is_deleted: false,
  },
];

export function getEditorialActivities(): Activity[] {
  return EDITORIAL_ACTIVITIES.map((a) => ({ ...a }));
}
